consumer:
  host: argus
  username: argus
  password: panoptes
  queue: frames
  ssl_ca: ssl/rootCA.pem

face_detector:
  type: 'tensorflow_faceboxes'
  min_pixels: 0

debug: False

notifier:
  type: classification

  classification:
    publisher:
      host: argus
      username: argus
      password: panoptes
      exchange: argus
      routing_key: faces
      ssl_ca: ssl/rootCA.pem

  # Avoid classification and send message to web with detection information
  web:
    publisher:
      host: argus
      username: argus
      password: panoptes
      exchange: argus
      routing_key: published_detected_faces
      ssl_ca: ssl/rootCA.pem

    db:
      database: argus
      host: argus
      port: 5432
      user: argus
      password: panoptes


logging:
  level: INFO

storage:
  host: argus
  port: 9500
  access_key: argus
  secret_key: panoptes

tracer:
  host: argus
  port: 6831

