consumer:
  host: localhost
  username: argus
  password: panoptes
  queue: frames

face_detector:
  configuration:
    type: 'tensorflow_faceboxes'

debug: False

publisher:
  host: localhost
  username: argus
  password: panoptes
  exchange: argus
  routing_key: faces

logging:
  host: localhost
  port: 12201

storage:
  host: localhost
  port: 9500
  access_key: argus
  secret_key: panoptes