consumer:
  host: localhost
  username: argus
  password: panoptes
  queue: frames

face_detector:
  type: 'tensorflow_faceboxes'

debug: False

publisher:
  host: localhost
  username: argus
  password: panoptes
  exchange: argus
  routing_key: faces

logging:
  level: DEBUG

storage:
  host: localhost
  port: 9500
  access_key: argus
  secret_key: panoptes

tracer:
  host: localhost
  port: 6831
