consumer:
  host: localhost
  username: argus
  password: panoptes
  queue: faces

face_embedder:
  configuration:
    type: 'pytorch_facenet'

face_classifier:
  model: '../model/svclassifier_edu_gabo_pytorch_facenet.pkl'
  threshold: 0.7

publisher_web:
  host: localhost
  username: argus
  password: panoptes
  exchange: argus
  routing_key: published_detected_faces

publisher_summarizer:
  host: localhost
  username: argus
  password: panoptes
  exchange: argus
  routing_key: summarize_detected_faces

logging:
  level: DEBUG

storage:
  host: localhost
  port: 9500
  access_key: argus
  secret_key: panoptes

db:
  database: argus
  host: localhost
  port: 5432
  user: argus
  password: panoptes

tracer:
  host: localhost
  port: 6831