services:
    minio:
        image: quay.io/minio/minio
        command: server /data --console-address ":9001"
        env_file:
            - configuration/minio/minio.env
        ports:
            - 9500:9000
            - 9501:9001
        volumes:
            - minio-data:/data
    postgres:
        image: postgres
        env_file:
            - configuration/postgres/postgresql.env
        restart: always
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
    rabbitmq:
        image: rabbitmq:3-management
        env_file:
            - configuration/rabbitmq/rabbitmq.env
        volumes:
            - ../ssl/:/etc/rabbitmq/ssl/
            - ./configuration/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
            - rabbitmq-data:/var/lib/rabbitmq/
            - rabbitmq-log:/var/log/rabbitmq/
        ports:
            - 1883:1883
            - 5671:5671
            - 5672:5672
            - 15672:15672
    jaeger:
        image: jaegertracing/all-in-one
        ports:
            - 6831:6831/udp
            - 14268:14268
            - 16686:16686
volumes:
    postgres-data:
    minio-data:
    rabbitmq-data:
    rabbitmq-log: